#!/bin/bash
MYAPPS=$HOME/desktop/myapps
DEST=${MYAPPS}/forensic-1.0

if [ -d "$DEST" ]
then
  rm -rf $DEST
  echo 'Removed old installation.'
fi

if [ ! -d "$MYAPPS" ]
then
  mkdir  $MYAPPS
fi

echo $DEST
cp ../target/forensic-1.0.zip $MYAPPS
cd $MYAPPS
unzip forensic-1.0.zip
